### ISSUE TITLE
Module for updating transaction metadata

### ISSUE THREAD

**Issue by george19871205** [sharetribe/flex-sdk-js#127]
Hello
I'm having issues with this node package when I try to update the transaction metadata.

Is it possible to add this function from flex-sdk-js package?

For now, this node package doesn't provide sdk.transactions.updateMetadata().

Is it possible to update the current node package? Or is there any other way that I can modify transaction protected data or metadata using sharetribe-flex-sdk?

Thanks in advance.
George.

**Comment by rap1ds** [comment]
Hi there, thanks for your message!

The only way you can modify the state of a transaction (incl. metadata) is via transitions. The transitions have `actions`, which will modify the state of the transaction.

One of the available actions is [`privileged-update-metadata`](https://www.sharetribe.com/docs/references/transaction-process-actions/#actionprivileged-update-metadata). When this action is in the transition, you can modify the transaction metadata (\*).

So let's say you have a transition called "add-secret-id" which has the `privileged-update-metadata` action and you want to add metadata `{"secretId": "123-123"}`. With SDK you can do it like this:

```js
sdk.transactions.transition({
  id: new UUID("transaction id here"),
  transition: "transition/add-secret-id",
  params: {metadata: {secretId: "123-123"}}
}
``` 

(\*) Keep in mind that this action is a privileged action, which means that you can only run it in a trusted context, i.e. not in a browser but in your Node.js server with client-secret

I'll close this issue, but feel free to add comments/questions on this thread.

**Comment by rap1ds** [comment]
Btw. with the Integration API it's possible to update the metadata without transitioning the transaction. To interact with the Integration API, you can use the Integration SDK (https://github.com/sharetribe/flex-integration-sdk-js) which indeed has what you were looking for, `integrationSdk.transactions.updateMetadata()`.
